apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: devops
data:
  REACT_APP_API_URL: http://backend-service:8080  # If using React
  # or for Angular: BACKEND_URL: http://backend-service:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nadinebenarbia/frontend:latest  # Will be replaced by pipeline
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devops
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Fixed port for easy access
  type: NodePort  # Exposed externally